### ISSUE TITLE
Deck store missing latest version

### ISSUE THREAD

**Issue by ChronosWing** [jurassicplayer/decky-autosuspend#1]
So only version 1.0.0 is showing on the decky store and it doesn’t install. I see here you are up to 1.2, is there some other way I should be installing the plugin?

**Comment by jurassicplayer** [comment]
For manual installation, you will need to use the terminal a little (decky-loader has some bugs with setting the right permissions for some folders atm) and a keyboard would be preferred (not required), but it's not a daunting task and hopefully these instructions will be easy enough to follow. Please follow them in order, from top to bottom.

1. Start the deck in Gaming Mode
2. Open Decky-Loader in the QAM
3. Go to Decky settings
4. Scroll down the General settings using the D-Pad/Joystick, not touch
5. On `Manual plugin install` section, keep navigating using the D-Pad/Joystick until the `URL` entry is highlighted
6. Press A to bring up the virtual keyboard, or use your own keyboard to add the following url:
   - `https://github.com/jurassicplayer/decky-autosuspend/releases/download/v1.2.0/decky-autosuspend.zip`
7. Press `Install` and `Confirm`
8. Go to desktop mode (`Steam` menu => `Power` => `Switch to Desktop`)
9. Open the start menu
10. Search and open the application called `Konsole`
11. Type in the following command
  - `sudo chown -R deck:deck ~/homebrew/plugins/decky-autosuspend && sudo chown -R deck:deck ~/homebrew/settings`
12. Press Enter to run the command (it will prompt for your password, which is the same one you used when you installed decky-loader)
13. Return to Gaming Mode and enjoy \o/

If for some reason decky-loader doesn't come back when returning to Gaming Mode, just restart the console (known issue occurring with decky atm). If there is a step you need more clarity on, or any issues you come across (in either setup or usage), feel free to mention it here or in the Steam Deck Homebrew discord (there is a dedicated AutoSuspend Support post in the plugin-forum section).

**Comment by ChronosWing** [comment]
Ok got it installed using the manual method. Noticed some bugs so far, one is probably a decky issue claiming the plugin needs an update but it wants to “update” to 1.0.0. The other I would consider a major bug is when charging the deck while also using it autosuspend just decides the ciritical level has been reached and suspends even though battery percentage is well above the 10% threshold I have it set to.

**Comment by jurassicplayer** [comment]
The needs an update thing is decky-loader. It doesn't really check versions so much as "is it different from what we have in the store".

For the major bug, I've been attempting to reproduce the issue, but haven't been able to. If it's a reproducible issue, please install v1.2.1 and follow the instructions [here](https://github.com/jurassicplayer/decky-autosuspend#obtaining-debugging-information) to get some debugging logs so I can get a gist of what is happening on your device.

**Comment by ChronosWing** [comment]
I’ll try to reproduce but I can explain what happened. Deck was close to 10% threshold, I plugged it in and continued to play a pretty demanding game. About 10 minutes in I got the toast notification from autosuspend that battery was low, battery was around 25-30% charged at that point. Then a few minutes later autosuspend put the deck to sleep.

**Comment by jurassicplayer** [comment]
@ChronosWing I believe I have found the issue (hopefully) and it will be fixed in the next release (v1.2.2+). I'm not sure if you did this during your testing, but reloading the plugin from the decky settings puts my plugin into a messy state where there would be more than one disconnected loop checking with the last settings before the reload for every reload.

**Comment by jurassicplayer** [comment]
@ChronosWing 
I've implemented the fix mentioned in my previous comment, and the odd autosuspending behavior should hopefully be resolved now in v1.3.0. You can follow the manual installation instructions or just wait until it is added to the decky plugin store. You will need to do at least ONE full reset if upgrading from a previous release to clear out the aforementioned messy state, but after that you should be good.

If you encounter the same issue again or find any additional issues, feel free to open up a new issue.
